version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
#      DATABASE_URL: postgres://postgres:mysecretpassword@postgres:5432/db
#      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - ./node_modules

  postgres:
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: db
